<?php
echo (pi());
"<br>";
echo(min(0, 150, 30, 20, -8, -200) . "<br>");
echo(max(0, 150, 30, 20, -8, -200));
echo (abs(-7.5)."<br>");
echo(sqrt(64) . "<br>");
echo(sqrt(0) . "<br>");
echo(sqrt(1) . "<br>");
echo(sqrt(9));
echo(round(0.60) . "<br>");
echo(round(0.50) . "<br>");
echo(round(0.49) . "<br>");
echo(round(-4.40) . "<br>");
echo(round(-4.60));
echo(rand())."<br>";
echo(rand(10, 100));
echo "<br>";
echo "asin() function";
echo"<br>";
echo (asin(0.64) . "<br>");
echo (asin(1 ). "<br>");
echo (asin(2.66) . "<br>");
echo (asin(-1 ). "<br>");
echo (asin( 3). "<br>");
echo "<br>";
echo "asinh() function";
echo "<br>";
echo (asinh(7) . "<br>");
echo (asinh(20 ). "<br>");
echo (asinh(2.66) . "<br>");
echo "<br>";
echo "atan() function";
echo"<br>";
echo (atan(7) . "<br>");
echo (atan(-7 ). "<br>");
echo (atan(2.66) . "<br>");
echo (atan(-2.66) . "<br>");
echo (atan(250) . "<br>");
echo "<br>";
echo "bindes";
echo bindec("0030") . "<br>";
echo bindec("021") . "<br>";
echo bindec("11000110011") . "<br>";
echo bindec("111");
echo "<br>";
echo "decbin";
echo "<br>";
echo decbin("3") ."<br>";
echo decbin("1") ."<br>";
echo decbin("1500") ."<br>";
echo decbin("7") ."<br>";
echo "<br>";
echo "decoct() function";
echo "<br>";
echo decoct("30") . "<br>";
echo decoct("10") . "<br>";
echo decoct("1587") . "<br>";
echo decoct("70");
echo "<br>";
echo "exp () function";
echo(exp(0) . "<br>");
echo(exp(1) . "<br>");
echo(exp(10) . "<br>");
echo(exp(4.8));
echo "<br>";



?>
