<?php
echo strlen("hello word!");
echo "<br>";
echo "strpbk";
echo "<br>";
echo strpbrk("hello world!","oe");
echo "<br>";
echo "strlower";
echo "<br>";
echo strtolower("hello");
echo "<br>";
echo strtoupper("hello world!");
echo "<br>";
echo "string";
echo "<br>";
$x ="Hello word!";
$y='hello word!';
echo $x;
 echo"<br>";
echo $y;
echo "<br>";
echo "strcount";
echo "<br>";
echo substr_count("Hello world. The world is nice","world");
echo "<br>";
echo "split";
echo "<br>";
$str = "Hello world!";
echo chunk_split($str,3,".");
echo "<br>";
echo "similar";
echo "<br>";
echo similar_text("hello world","hello peter");
echo "<br>";
echo "sha10";
echo "<br>";
$str = "Hello";
echo sha1($str);
echo "<br>";
echo "ltrim";
echo "<br>";
$str = "Hello World!";
echo $str . "<br>";
echo ltrim($str,"Hello");
echo "<br>";
echo "levenshtein";
echo "<br>";
echo levenshtein("Hello World","ello World");
echo "<br>";
echo levenshtein("Hello World","ello World",10,20,30);
echo "<br>";
echo "join";
echo "<br>";
echo "<br>";
$arr =array('Hello','World!','Beautiful','Day!');
echo join("",$arr);
echo "ireplace";
echo str_ireplace("WORLD","Peter","Hello good world!");

?>